spring:
  application:
    name: PTM-back
  datasource:
    url: jdbc:oracle:thin:@//<DB_HOST>:<DB_PORT>/<DB_NAME>
    username: <DB_USER>
    password: <DB_PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://<DOMAIN>.us.auth0.com/
auth0:
  audience: https://<DOMAIN>.us.auth0.com/api/v2/
  domain: https://<DOMAIN>.us.auth0.com
  clientId: '<CLIENT_ID>'
  clientSecret: '<CLIENT_SECRET>'

server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    org.springframework.web: debug
    org.hibernate: error
